export type Program = {
  status: "Ofertados" | "En curso" | "Finalizado";
  img: string;
  to: string;
  price: string;
  category: string;
  meta: {
    name: string;
    description: string;
    requirements: string[];
    details_raw: string[];
    details: {
      grado_académico: string;
      costo_por_modulo: string;
      descuento: string;
      modalidad: string[];
      fecha_de_inicio: string;
    };
  };
};

type ProgramData = {
  diplomados: Program[];
  maestrias: Program[];
  doctorados: Program[];
};

export const data : ProgramData= {
  diplomados: [
    {
      status: "En curso",
      img: "/images/programas/dip-ciberseguridad-1v-03.jpg",
      to: "/diplomados/dip-ciberseguridad-1v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN CIBERSEGURIDAD - 1ª VERSIÓN",
        description:
          "El Diplomado en Ciberseguridad te propone adquirir conocimientos, destrezas y capacidades para proteger sistemas, redes y datos, especializándote en las últimas tecnologías y estrategias de defensa digital. Dominarás temas clave como Fundamentos y Gestión de la Ciberseguridad bajo la ISO/IEC 27032 , Inteligencia de Amenazas y OSINT , Hacking Ético y Pruebas de Penetración (Pentesting) , Análisis Forense Digital y Respuesta a Incidentes (DFIR) , y Centro de Operaciones de Seguridad (SOC) y Monitoreo. Este programa está diseñado a tus necesidades, garantizándote un aprendizaje profundo y práctico en el campo de la Ciberseguridad. ¡Prepárate para un futuro donde serás la primera línea de defensa digital!",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Director de Posgrado(Ing. MSc. Ronald Patiño Tito)",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:917 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Doble Titulacion , Profesionales",
          "Fecha de Inicio:01 de Septiembre 2025",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "917 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Doble titulacion", "Profesionales"],
          fecha_de_inicio: "01 de Septiembre 2025",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-mecatronicaedi-3v-05.jpg",
      to: "/diplomados/dip-mecatronicaedi-3v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN MECATRÓNICA CON ENFOQUE EN DISEÑO INDUSTRIAL - 3ª VERSIÓN",
        description:
          "El Diplomado tiene como propósito de este es, ampliar las destrezas profesionales, desarrollando competencias de aplicación especializadas en el área de mecánica, electrónica, automatización y materiales, para responder a las necesidades de las empresas del sector manufacturero, petrolero, agrícola y de servicios del país y el exterior.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Director de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:917 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Doble Titulacion , Profesionales",
          "Fecha de Inicio:03 de Septiembre 2025",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "917 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Doble titulacion", "Profesionales"],
          fecha_de_inicio: "03 de Septiembre 2025",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-edusup-19v-01.jpg",
      to: "/diplomados/dip-edusup-19v",
      price: "Bs 4500",
      category: "Profesionales",
      meta: {
        name: "DIPLOMADO EN EDUCACIÓN SUPERIOR BASADA EN COMPETENCIAS PARA CIENCIAS Y TECNOLOGÍA - 19ª VERSIÓN",
        description:
          "Los estudiantes aplicaran la metodología de formación basada en competencias y asimismo desarrollaran y profundizaran sus conocimientos en la pedagogía y didáctica, nuevos métodos, metodología y evaluación y además de novedosas habilidades en la planificación didáctica, elaboración de planes globales, uso de las tecnologías de información y de comunicación y diseños curriculares en la educación superior enfocado al área de la ciencia y tecnología.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Director de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:750 Bs",
          "Descuento:Pago al contado tiene un descuento del 10 %",
          "Modalidad:Profesionales",
          "Fecha de Inicio:17 de Noviembre de 2025 - Ultimos Cupos!!!!",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "750 Bs",
          descuento: "Pago al contado tiene un descuento del 10 %",
          modalidad: ["Profesionales"],
          fecha_de_inicio: "17 de Noviembre de 2025 - Ultimos Cupos!!!!",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-isoldadura-1v-07.jpg",
      to: "/diplomados/dip-isoldadura-1v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN INGENIERÍA DE SOLDADURA - 1ra. Versión",
        description:
          "El diplomado en Ingeniería de Soldadura tiene como propósito fundamental fortalecer los conocimientos y proporcionar herramientas necesarias para el diseño, ejecución y supervisión de procesos de soldadura en el ámbito industrial. Se enfoca en integrar la teoría con la práctica, reconociendo la importancia de la experiencia directa en la adquisición de habilidades técnicas. El programa busca desarrollar habilidades críticas en los participantes para identificar y resolver problemas relacionados con la soldadura en la industria. Además, se enfoca en la implementación de planes de mantenimiento como una estrategia efectiva para garantizar la calidad y seguridad en los procesos de soldadura.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:917 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Modalidad de Graduación por Diplomado, Profesionales",
          "Fecha de Inicio:22 de Octubre de 2025",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "917 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Modalidad de graduación por diplomado", "Profesionales"],
          fecha_de_inicio: "22 de Octubre de 2025",
        },
      },
    },
    {
      status: "Ofertados",
      img: "/images/programas/dip-cdatos-4v-03.jpg",
      to: "/diplomados/dip-cdatos-4v",
      price: "Bs 5500",
      category: "Profesionales",
      meta: {
        name: "DIPLOMADO EN CIENCIA DE DATOS - 4ª Versión",
        description:
          "El Diplomado en Ciencia de Datos proporcionará a los participantes una comprensión profunda en el procesamiento de datos, ahondando en la extracción, clasificación y análisis de la información en forma de datos de una empresa o negocio, tomando en consideración el análisis estadístico, la programación y el machine learning. Para ello se desarrollan habilidades de aplicación de parámetros estadísticos considerando la programación en el lenguaje Python, la preparación de datos considerando las técnicas de almacenamiento de manera ordenada, el análisis de volúmenes de datos de gran magnitud, la automatización de procesos de aprendizaje en función a la tendencia de los datos y la visualización de los mismos considerando representaciones gráficas que faciliten su evaluación.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:917 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Doble Titulacion , Profesionales",
          "Fecha de Inicio:16 de Febrero de 2026",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "917 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Doble titulacion", "Profesionales"],
          fecha_de_inicio: "16 de Febrero de 2026",
        },
      },
    },
    {
      status: "Ofertados",
      img: "/images/programas/dip-tbiocombustible-1v-19.jpg",
      to: "/diplomados/dip-tbiocombustible-1v",
      price: "Bs 5600",
      category: "Profesionales",
      meta: {
        name: "DIPLOMADO EN TECNOLOGÍAS DE BIOCOMBUSTIBLES E HIDRÓGENO – 1RA. VERSIÓN",
        description:
          "El Diplomado tiene como propósito fortalecer los conocimientos y proporcionar herramientas para analizar las tecnologías avanzadas de producción de biocombustibles e hidrógeno sus beneficios y riesgos, así como sus impactos en la economía y el medio ambiente, desarrollando la competencia necesaria para que los estudiantes egresados y profesionales sean capaces de elaborar proyectos de estas áreas a diversas escalas, para responder a la necesidad de diversificar la matriz energética en el país.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:800 Bs",
          "Descuento:Pago al contado tiene un descuento del 10% del monto total.",
          "Modalidad:Profesionales",
          "Fecha de Inicio:16 de Febrero de 2026",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "800 Bs",
          descuento:
            "Pago al contado tiene un descuento del 10% del monto total.",
          modalidad: ["Profesionales"],
          fecha_de_inicio: "16 de Febrero de 2026",
        },
      },
    },
    {
      status: "Ofertados",
      img: "/images/programas/dip-biomedica-2v-07.jpg",
      to: "/diplomados/dip-biomedica-2v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN TECNOLOGÍA BIOMÉDICA - 2da. Versión",
        description:
          "Desarrollar habilidades técnicas para el diseño, implementación y mantenimiento de dispositivos médicos, equipos de diagnóstico y otras tecnologías relacionadas, creando competencias de aplicación especializados en el área de Salud.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:786 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Modalidad de Graduación por Diplomado, Profesionales",
          "Fecha de Inicio:16 de Febrero de 2026",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "786 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Modalidad de graduación por diplomado", "Profesionales"],
          fecha_de_inicio: "16 de Febrero de 2026",
        },
      },
    },
    {
      status: "Ofertados",
      img: "/images/programas/dip-trabaltoriesgo-3v-06.jpg",
      to: "/diplomados/dip-trabaltoriesgo-3v",
      price: "Bs 5500",
      category: "Profesionales,Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN TRABAJOS DE ALTO RIESGO (Altura, Soldadura, Electricidad y Excavación)- 3ra. Versión",
        description:
          "El Diplomado en Trabajos de Alto Riesgo (Altura, Soldadura, Electricidad y Excavación) tiene como propósito de este es, ampliar las destrezas profesionales, desarrollando competencias de aplicación especializadas en el área industrial, para responder a las necesidades de concientización, difusión de normas y procedimientos para trabajo seguro en las empresas del sector industrial.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:917 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Modalidad de Graduación por Diplomado, Profesionales",
          "Fecha de Inicio:16 de Febrero de 2026 - Ultimas plazaz!!",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "917 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Modalidad de graduación por diplomado", "Profesionales"],
          fecha_de_inicio: "16 de Febrero de 2026 - Ultimas plazaz!!",
        },
      },
    },
    {
      status: "Ofertados",
      img: "/images/programas/dip-iergonomia-7v-07.jpg",
      to: "/diplomados/dip-iergonomia-7v",
      price: "Bs 4500",
      category: "Profesionales",
      meta: {
        name: "DIPLOMADO EN INGENIERÍA EN SEGURIDAD INDUSTRIAL Y ERGONOMÍA - 9ª VERSIÓN",
        description:
          "El diplomado Ingeniería en Seguridad Industrial y Ergonomía tiene como propósito coadyuvar en la formación de los profesionales de ingeniería en seguridad, para que, a través de la aplicación ética y responsable de los conocimientos y experiencias adquiridos en el programa, sean capaces de hacer uso de metodologías innovadoras y eficientes en los aspectos de seguridad y áreas mencionadas.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:563 Bs",
          "Descuento:10 % de descuento por pago al contado",
          "Modalidad:Profesionales",
          "Fecha de Inicio:16 de Febrero de 2026 - Ultimas plazaz!!",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "563 Bs",
          descuento: "10 % de descuento por pago al contado",
          modalidad: ["Profesionales"],
          fecha_de_inicio: "16 de Febrero de 2026 - Ultimas plazaz!!",
        },
      },
    },
    {
      status: "Ofertados",
      img: "/images/programas/dip-lutribologia-1v-11.jpg",
      to: "/diplomados/dip-lutribologia-1v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN LUBRICACIÓN Y TRIBOLOGÍA PARA LA OPTIMIZACIÓN DE SISTEMAS MECÁNICOS - 1ª Versión",
        description:
          "El diplomado pretende ampliar las destrezas profesionales, con conocimientos avanzados y competencias técnicas en estas disciplinas, permitiéndoles optimizar el mantenimiento predictivo y preventivo de lubricación, mejorar la eficiencia energética, cumplir con normativas ambientales y de seguridad, actualizándose con los avances tecnológicos para mejorar la empleabilidad y competitividad de los participantes quienes serán altamente valorados en diversos sectores industriales.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:786 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Modalidad de Graduación por Diplomado, Profesionales",
          "Fecha de Inicio:16 de Febrero 2026",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "786 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Modalidad de graduación por diplomado", "Profesionales"],
          fecha_de_inicio: "16 de Febrero 2026",
        },
      },
    },
    {
      status: "Ofertados",
      img: "/images/programas/dip-estadistica-4v-08.jpg",
      to: "/diplomados/dip-estadistica-4v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN ESTADÍSTICA APLICADA A LA TOMA DE DECISIONES - 4TA. VERSIÓN",
        description:
          "El diplomado tiene como propósito el proporcionar a los participantes una sólida formación en la aplicación de la estadística, fortaleciendo los conocimientos, proporcionando herramientas y desarrollando competencias que permitan potenciar capacidades de organización, descripción y predicción del comportamiento de datos, enmarcados en la gestión de los mismos utilizando software especializado para la elaboración de algoritmos de automatización, dando soporte a la toma de decisiones.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:917 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Modalidad de Graduación por Diplomado, Profesionales",
          "Fecha de Inicio:16 de Febrero de 2026",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "917 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Modalidad de graduación por diplomado", "Profesionales"],
          fecha_de_inicio: "16 de Febrero de 2026",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-ccialimentos-10v-03.jpg",
      to: "/diplomados/dip-ccialimentos-10v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN CONTROL DE CALIDAD E INOCUIDAD DE LOS ALIMENTOS – 10MA. VERSIÓN",
        description:
          "El diplomado en Control de Calidad e Inocuidad de los Alimentos tiene como propósito la formación avanzada de profesionales y egresados interesados en desarrollar aptitudes que exige la industria de alimentos para así responder a las demandas laborales en cuanto a inocuidad, legislación nacional e internacional, control de calidad, producción y seguridad e higiene, a través de un conjunto sistemático y coherente de conocimiento teórico-práctico en el área, que les permita complementar, actualizar y perfeccionar sus competencias profesionales.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:786 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Doble Titulacion , Profesionales",
          "Fecha de Inicio:16 de Cotubre de 2025",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "786 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Doble titulacion", "Profesionales"],
          fecha_de_inicio: "16 de Cotubre de 2025",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-pquimicos-10v-17.jpg",
      to: "/diplomados/dip-pquimicos-10v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN PROCESOS QUÍMICOS – 10MA. VERSIÓN",
        description:
          "El diplomado en Control de Calidad e Inocuidad de los Alimentos tiene como propósito la formación avanzada de profesionales y egresados interesados en desarrollar aptitudes que exige la industria de alimentos para así responder a las demandas laborales en cuanto a inocuidad, legislación nacional e internacional, control de calidad, producción y seguridad e higiene, a través de un conjunto sistemático y coherente de conocimiento teórico-práctico en el área, que les permita complementar, actualizar y perfeccionar sus competencias profesionales.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:786 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Modalidad de Graduación por Diplomado, Profesionales",
          "Fecha de Inicio:06 de Octubre de 2025 - Inicio Confirmado",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "786 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Modalidad de graduación por diplomado", "Profesionales"],
          fecha_de_inicio: "06 de Octubre de 2025 - Inicio Confirmado",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-hleanm-1v-10.jpg",
      to: "/diplomados/dip-hleanm-1v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN HERRAMIENTAS LEAN MANUFACTURING – 1ª VERSIÓN",
        description:
          "El propósito del diplomado es capacitar a los profesionales en la implementación de metodologías y herramientas orientadas a la optimización de procesos productivos, la eliminación de desperdicios y la mejora continua en las operaciones industriales. A través de este programa, los participantes desarrollarán habilidades clave como la identificación y análisis de ineficiencias, la aplicación de técnicas de resolución de problemas, y la gestión eficiente de recursos. Además, aprenderán a liderar iniciativas de cambio organizacional con un enfoque en la creación de valor, la mejora de la calidad, y la reducción de costos, todo ello alineado con los principios de Herramientas Lean Manufacturing.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Director de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:917 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Modalidad de Titulación, Profesionales",
          "Fecha de Inicio:11 de Septiembre de 2025 - Inicio Confirmado",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "917 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Modalidad de titulación", "Profesionales"],
          fecha_de_inicio: "11 de Septiembre de 2025 - Inicio Confirmado",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-gestagua-9v-08.jpg",
      to: "/diplomados/dip-gestagua-9v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN GESTIÓN DEL AGUA - 9ª VERSIÓN",
        description:
          "El Diplomado Gestión del Agua tiene como propósito desarrollar y potencializar las capacidades, habilidades, destrezas y conocimientos técnicos científicos, de los futuros profesionales en Ingeniería Civil, desarrollando una competencia de aplicación especializada en diversos ámbitos de la Gestión del agua como; la gestión ambiental del recurso hídrico, la calidad de agua y tecnologías de tratamiento, uso eficiente del agua y gestión de riego, Aplicación de hidráulica avanzada y la evaluación del riesgos asociado al cambio climático.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:917 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Modalidad de Graduación por Diplomado, Profesionales",
          "Fecha de Inicio:26 de Septiembre de 2025 - Reserva tu Cupo!!!",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "917 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Modalidad de graduación por diplomado", "Profesionales"],
          fecha_de_inicio: "26 de Septiembre de 2025 - Reserva tu Cupo!!!",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-mantenimientoi-7v-05.jpg",
      to: "/diplomados/dip-mantenimientoi-7v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN MANTENIMIENTO INDUSTRIAL - 7ª Versión",
        description:
          "El diplomado plantea de forma que el estudiante (profesional) pueda desarrollar destrezas y habilidades técnicas y generar creatividad que responda a las exigencias de la demanda del sector industrial, orientadas a una mejor gestión de recursos para el ámbito del Mantenimiento industrial y paradas de planta y equipos.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:917 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Modalidad de Graduación por Diplomado, Profesionales",
          "Fecha de Inicio:Inscripciones hasta el 29 de Septiembre de 2025",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "917 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Modalidad de graduación por diplomado", "Profesionales"],
          fecha_de_inicio: "Inscripciones hasta el 29 de Septiembre de 2025",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-iemprendimiento-2v-03.jpg",
      to: "/diplomados/dip-iemprendimiento-2v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN INGENIERÍA DEL EMPRENDIMIENTO INDUSTRIAL - 2ª Versión",
        description:
          "El diplomado plantea de forma que el estudiante (profesional) pueda desarrollar habilidades que integran conocimientos técnicos con competencias industriales. Este enfoque integral busca preparar a los profesionales para liderar y gestionar proyectos innovadores y startups, fomentar la creatividad y la innovación, mejorar la competitividad y contribuir al desarrollo económico y social.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:786 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Doble Titulacion , Profesionales",
          "Fecha de Inicio:19 de Septiembre 2025",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "786 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Doble titulacion", "Profesionales"],
          fecha_de_inicio: "19 de Septiembre 2025",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-infvial-7v-04.jpg",
      to: "/diplomados/dip-infvial-7v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN INFRAESTRUCTURA VIAL – 7ª VERSIÓN",
        description:
          "El diplomado tiene como propósito dotar de conocimientos técnicos científicos, habilidades y destrezas a estudiantes y/o profesionales, desarrollando competencias de aplicación especializada en el área de ingeniería en infraestructura, para responder a las necesidades sociales en proyectos de ingeniería civil",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:786 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Modalidad de Graduación por Diplomado, Profesionales",
          "Fecha de Inicio:23 de Septiembre de 2025",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "786 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Modalidad de graduación por diplomado", "Profesionales"],
          fecha_de_inicio: "23 de Septiembre de 2025",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-ingestructuras-6v-04.jpg",
      to: "/diplomados/dip-ingestructuras-6v",
      price: "Bs 5500",
      category: "Profesionales",
      meta: {
        name: "DIPLOMADO EN INGENIERÍA DE ESTRUCTURAS – 6ª VERSIÓN",
        description:
          "El diplomado en Ingeniería de Estructuras, en su quinta versión, tiene como propósito formar integralmente a los profesionales de la ingeniería civil en la formulación y desarrollo de proyectos estructurales. Este programa busca proporcionar una educación avanzada que permita a los participantes diseñar obras civiles seguras y económicas, cumpliendo con la normativa técnica-legal vigente. A través de la adquisición de conocimientos avanzados y el uso de herramientas tecnológicas de última generación, los ingenieros serán capaces de enfrentar los desafíos actuales y futuros en el campo de las estructuras, garantizando la estabilidad y durabilidad de las construcciones",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Director de Posgrado(Ing. MSc. Ronald Patiño Tito)",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:786 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Modalidad de Titulación, Profesionales",
          "Fecha de Inicio:11 de Agosto de 2025 - Inicio Confirmado",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "786 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Modalidad de titulación", "Profesionales"],
          fecha_de_inicio: "11 de Agosto de 2025 - Inicio Confirmado",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-gproduccionympi-5v-04.jpg",
      to: "/diplomados/dip-gproduccionympi-5v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN GESTIÓN DE LA PRODUCCIÓN Y MEJORA DE PROCESOS INDUSTRIALES - 5ª VERSIÓN",
        description:
          "Proporcionar a los participantes una sólida formación del área de producción, así como los conocimientos teóricos y prácticos necesarios para desarrollar habilidades en la gestión eficiente de la producción y la mejora continua de los procesos industriales; aplicando estrategias gerenciales efectivas, aumentando la productividad, reduciendo costos y garantizando la calidad en entornos industriales.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Director de Posgrado(Ing. MSc. Ronald Patiño Tito)",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:786 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Doble Titulacion , Profesionales",
          "Fecha de Inicio:11 de Agosto de 2025 - Ultimas Plazas!!!!",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "786 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Doble titulacion", "Profesionales"],
          fecha_de_inicio: "11 de Agosto de 2025 - Ultimas Plazas!!!!",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-projectm-4v-03.jpg",
      to: "/diplomados/dip-projectm-4v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN PROJECT MANAGEMENT – 3RA. VERSIÓN",
        description:
          "Aplicar técnicas y metodologías avanzadas según el PMBOK del PMI. A través de una educación rigurosa y orientada a la práctica, desarrollando las habilidades necesarias para planificar, ejecutar y controlar proyectos de manera eficiente, implementando sistemas de gestión en la comunicación, calidad y recursos. Para reducir los factores de riesgos involucrados en todo el ciclo del proyecto.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Director de Posgrado(Ing. MSc. Ronald Patiño Tito)",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:786 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Doble Titulacion , Profesionales",
          "Fecha de Inicio:18 de Agosto de 2025",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "786 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Doble titulacion", "Profesionales"],
          fecha_de_inicio: "18 de Agosto de 2025",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-sisepotencia-1v-03.jpg",
      to: "/diplomados/dip-sisepotencia-1v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN PROTECCIÓN DE SISTEMAS ELÉCTRICOS DE POTENCIA MEDIANTE RELÉS - 1ª VERSIÓN",
        description:
          "El Diplomado tiene como propósito desarrollar en los participantes fortalecer conocimientos y proporcionar metodologías y herramientas para analizar, diseñar, coordinar y evaluar sistemas de protección en sistemas de generación, transmisión y redes de distribución, aplicando principios y filosofías de protección eléctrica mediante filosofías vigentes y herramientas digitales avanzadas, la práctica dentro el programa es esencial en la integración de conceptos, procedimientos y actitudes, además de desarrollar un sentido crítico para interpretar y diagnosticar fallas eléctricas mediante análisis de oscilografias y pruebas en campo, asegurando la confiabilidad y seguridad en la operación del sistema eléctrico.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Director de Posgrado(Ing. MSc. Ronald Patiño Tito)",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:917 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Doble Titulacion , Profesionales",
          "Fecha de Inicio:11 de Agosto 2025 - Cupo Lleno!!!",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "917 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Doble titulacion", "Profesionales"],
          fecha_de_inicio: "11 de Agosto 2025 - Cupo Lleno!!!",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-supervisionf-1v-02.jpg",
      to: "/diplomados/dip-supervisionf-1v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN DIRECCIÓN, SUPERVISIÓN Y FISCALIZACIÓN DE OBRAS CIVILES - 1ª VERSIÓN",
        description:
          "El Diplomado en Dirección, Supervisión y Fiscalización de Obras Civiles tiene como propósito desarrollar en los participantes las habilidades necesarias para gestionar, supervisar y fiscalizar proyectos de construcción de manera eficiente, garantizando la calidad, seguridad y sostenibilidad en cada etapa del proceso.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Director de Posgrado(Ing. MSc. Ronald Patiño Tito)",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:917 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Doble Titulacion , Profesionales",
          "Fecha de Inicio:04 de Agosto 2025 - Cupo Lleno!!!",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "917 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Doble titulacion", "Profesionales"],
          fecha_de_inicio: "04 de Agosto 2025 - Cupo Lleno!!!",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-iaedusup-1v-08.jpg",
      to: "/diplomados/dip-iaedusup-1v",
      price: "Bs 4500",
      category: "Profesionales",
      meta: {
        name: "DIPLOMADO EN INTELIGENCIA ARTIFICIAL E INNOVACIÓN TECNOLÓGICA EN LA EDUCACIÓN SUPERIOR POR COMPETENCIAS PARA CIENCIAS Y TECNOLOGÍA - 1ª VERSIÓN",
        description:
          "El Diplomado en Inteligencia Artificial e Innovación Tecnológica en la Educación Superior por Competencias para Ciencias y Tecnología es capacitar a los docentes y gestores educativos en el diseño, implementación y evaluación de procesos pedagógicos centrados en el desarrollo de competencias, mediante el uso estratégico de la inteligencia artificial. Este diplomado busca ofrecer herramientas tecnológicas avanzadas que permitan personalizar el aprendizaje, optimizar la evaluación de competencias y mejorar la gestión educativa, fomentando una educación más dinámica, interactiva y adaptada a las necesidades individuales de los estudiantes. Además, promueve una reflexión ética sobre el uso de la tecnología en el ámbito educativo, preparando a los participantes para liderar la transformación digital en sus instituciones y asegurar una enseñanza de calidad en un entorno en constante cambio.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Director de Posgrado(Ing. MSc. Ronald Patiño Tito)",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:750 Bs",
          "Descuento:Pago al contado tiene un descuento del 10 %",
          "Modalidad:Profesionales",
          "Fecha de Inicio:14 de Julio de 2025",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "750 Bs",
          descuento: "Pago al contado tiene un descuento del 10 %",
          modalidad: ["Profesionales"],
          fecha_de_inicio: "14 de Julio de 2025",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-ingambiental-8v-07.jpg",
      to: "/diplomados/dip-ingambiental-8v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN INGENIERÍA AMBIENTAL - 8va. Versión",
        description:
          "El diplomado tiene como propósito, desarrollar una competencia de aplicación especializada en el área de gestión del medio ambiente aplicada al área de ingeniería, para responder a las necesidades del sector empresarial este conformado por las empresas de manufactura y de servicios, que tienen prioridades de implementar Sistemas de Gestión Ambiental.",
        requirements: [
          "Carta de solicitud de inscripción dirigido al Director de Posgrado(Ing. MSc. Ronald Patiño Tito)",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico Actualizado emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:917 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Doble Titulacion , Profesionales",
          "Fecha de Inicio:11 de Agosto de 2025",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "917 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Doble titulacion", "Profesionales"],
          fecha_de_inicio: "11 de Agosto de 2025",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-icpuentes-4v-05.jpg",
      to: "/diplomados/dip-icpuentes-4v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado",
      meta: {
        name: "DIPLOMADO EN INGENIERÍA CIVIL EN PUENTES - 4ª VERSIÓN",
        description:
          "El Diplomado en Ingenieria civil en puentes proporciona al participante las herramientas necesarias para el estudio, diseño, construcción y mantenimiento de estructuras de puentes en hormigón armado y presforzado, mediante el manejo de tecnologías actualizadas de acuerdo con las normativas vigentes y las características geológicas, geotécnicas y topográficas del proyecto.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Director de Posgrado(Ing. MSc. Ronald Patiño Tito)",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:786 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Modalidad de Titulación, Profesionales",
          "Fecha de Inicio:11 de Junio de 2025",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "786 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Modalidad de titulación", "Profesionales"],
          fecha_de_inicio: "11 de Junio de 2025",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/dip-ccialimentos-9v-03.jpg",
      to: "/diplomados/dip-ccialimentos-9v",
      price: "Bs 5500",
      category: "Profesionales, Modalidad de Graduación por Diplomado,",
      meta: {
        name: "DIPLOMADO EN CONTROL DE CALIDAD E INOCUIDAD DE LOS ALIMENTOS – 9NA. VERSIÓN",
        description:
          "El diplomado en Control de Calidad e Inocuidad de los Alimentos tiene como propósito la formación avanzada de profesionales y egresados interesados en desarrollar aptitudes que exige la industria de alimentos para así responder a las demandas laborales en cuanto a inocuidad, legislación nacional e internacional, control de calidad, producción y seguridad e higiene, a través de un conjunto sistemático y coherente de conocimiento teórico-práctico en el área, que les permita complementar, actualizar y perfeccionar sus competencias profesionales.",
        requirements: [
          "Carta de solicitud de inscripción dirigida a la Director de Posgrado(Ing. MSc. Ronald Patiño Tito)",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
          "Certificado de Conclusión de Estudios(expedido por Dirección de Carrera, requisito para interesados en la Modalidad de Titulación)",
          "Kardex Académico emitido por la Unidad de KARDEX FCyT(Requisito para los interesados de Modalidad en Titulación)",
        ],
        details_raw: [
          "Grado Académico:Diplomado",
          "Costo por modulo:786 Bs",
          "Descuento:No aplica descuentos",
          "Modalidad:Doble Titulacion , Profesionales",
          "Fecha de Inicio:31 de Marzo de 2025",
        ],
        details: {
          grado_académico: "Diplomado",
          costo_por_modulo: "786 Bs",
          descuento: "No aplica descuentos",
          modalidad: ["Doble titulacion", "Profesionales"],
          fecha_de_inicio: "31 de Marzo de 2025",
        },
      },
    },
  ],
  maestrias: [
    {
      status: "En curso",
      img: "/images/programas/maes-swia-1v-03.jpg",
      to: "/maestrias/maes-swia-1v",
      price: "Bs. 20.000",
      category: "Profesionales",
      meta: {
        name: "MAESTRÍA EN DESARROLLO DE PRODUCTOS DE SOFTWARE CON INTELIGENCIA ARTIFICIAL - 1ª VERSIÓN",
        description: "",
        requirements: [
          "Carta de solicitud de inscripción dirigido a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
        ],
        details_raw: [
          "Grado Académico:Maestria",
          "Costo por modulo:1.333,00 Bs",
          "Descuento:Pago al contado tiene un descuento del 10% del monto total.",
          "Modalidad:Profesionales",
          "Fecha de Inicio:24 de Noviembre de 2025",
        ],
        details: {
          grado_académico: "Maestria",
          costo_por_modulo: "1.333,00 Bs",
          descuento:
            "Pago al contado tiene un descuento del 10% del monto total.",
          modalidad: ["Profesionales"],
          fecha_de_inicio: "24 de Noviembre de 2025",
        },
      },
    },
    {
      status: "Ofertados",
      img: "/images/programas/maes-imanufactura-1v-09.jpg",
      to: "/maestrias/maes-imanufactura-1v",
      price: "Bs. 22.610",
      category: "Profesionales",
      meta: {
        name: "MAESTRÍA EN INGENIERÍA DE MANUFACTURA - 1ª VERSIÓN",
        description:
          "La maestría tiene como propósito fundamental capacitar a profesionales para el diseño avanzado de maquinaria y sus componentes, abarcando desde la selección óptima de materiales y métodos de fabricación hasta la integración de la automatización, siempre con un enfoque primordial en la fiabilidad y seguridad de los sistemas. Se espera los participantes desarrollen una capacidad creativa e innovadora para la gestión del diseño de maquinaria, permitiéndoles identificar y proponer soluciones originales a diversos problemas y requerimientos del sector. Esto incluye el fomento de habilidades de liderazgo esenciales para la gestión integral de proyectos, desde la concepción y fabricación hasta la puesta en marcha de maquinaria compleja. Finalmente, el programa busca inculcar una profunda ética profesional y un sentido de la responsabilidad intrínseco a la asunción de este tipo de proyectos. De esta manera, garantizamos que los futuros egresados puedan insertarse en procesos de manufactura con la capacidad de lograr resultados predecibles y sostenibles, siempre bajo un marco de integridad y compromiso ético.",
        requirements: [
          "Carta de solicitud de inscripción dirigido a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
        ],
        details_raw: [
          "Grado Académico:Maestria",
          "Costo por modulo:1.615 Bs",
          "Descuento:Pago al contado tiene un descuento del 10% del monto total.",
          "Modalidad:Profesionales",
          "Fecha de Inicio:16 de Febrero de 2026",
        ],
        details: {
          grado_académico: "Maestria",
          costo_por_modulo: "1.615 Bs",
          descuento:
            "Pago al contado tiene un descuento del 10% del monto total.",
          modalidad: ["Profesionales"],
          fecha_de_inicio: "16 de Febrero de 2026",
        },
      },
    },
    {
      status: "Ofertados",
      img: "/images/programas/maes-sigcma-v15-11.jpg",
      to: "/maestrias/maes-sigcma-v15",
      price: "Bs. 23.655",
      category: "Profesionales",
      meta: {
        name: "MAESTRÍA EN SISTEMAS INTEGRADOS DE GESTIÓN DE CALIDAD, MEDIO AMBIENTE Y SEGURIDAD - 15 VERSIÓN",
        description:
          "La maestría tiene como propósitos, desarrollar competencias en el área de los sistemas gestión de calidad, medio ambiente y seguridad, para responder al sector industrial y formación de recursos humanos de las empresas de manufactura y de servicios, que tienen prioridades de implementar sistemas de gestión, de acuerdo con la normativa nacional e internacional.",
        requirements: [
          "Carta de solicitud de inscripción dirigido a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
        ],
        details_raw: [
          "Grado Académico:Maestria",
          "Costo por modulo:1.245 Bs",
          "Descuento:Pago al contado tiene un descuento del 10% del monto total.",
          "Modalidad:Profesionales",
          "Fecha de Inicio:26 de Enero de 2026",
        ],
        details: {
          grado_académico: "Maestria",
          costo_por_modulo: "1.245 Bs",
          descuento:
            "Pago al contado tiene un descuento del 10% del monto total.",
          modalidad: ["Profesionales"],
          fecha_de_inicio: "26 de Enero de 2026",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/maes-iaedusup-1v-05.jpg",
      to: "/maestrias/maes-iaedusup-1v",
      price: "Bs. 12.500,00",
      category: "Profesionales",
      meta: {
        name: "MAESTRÍA EN INTELIGENCIA ARTIFICIAL E INNOVACIÓN TECNOLÓGICA EN LA EDUCACIÓN SUPERIOR - 1ª VERSIÓN",
        description:
          "La maestría en Inteligencia Artificial e Innovación Tecnológica en la Educación Superior es un profesional dedicado a la integración y aplicación de tecnologías emergentes, particularmente la inteligencia artificial (IA), para transformar y mejorar los procesos educativos en el ámbito universitario. Este profesional trabaja en el diseño, implementación y evaluación de soluciones tecnológicas que optimicen la enseñanza, el aprendizaje y la gestión institucional, promoviendo un entorno educativo adaptativo, innovador y basado en datos.",
        requirements: [
          "Carta de solicitud de inscripción dirigido a la Directora de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
        ],
        details_raw: [
          "Grado Académico:Maestria",
          "Costo por modulo:833,00 Bs",
          "Descuento:Pago al contado tiene un descuento del 10% del monto total.",
          "Modalidad:Profesionales",
          "Fecha de Inicio:Octubre de 2025",
        ],
        details: {
          grado_académico: "Maestria",
          costo_por_modulo: "833,00 Bs",
          descuento:
            "Pago al contado tiene un descuento del 10% del monto total.",
          modalidad: ["Profesionales"],
          fecha_de_inicio: "Octubre de 2025",
        },
      },
    },
    {
      status: "En curso",
      img: "/images/programas/maes-logisticaegcs-1v-12.jpg",
      to: "/maestrias/maes-logisticaegcs-1v",
      price: "Bs. 22.269",
      category: "Profesionales",
      meta: {
        name: "MAESTRÍA EN LOGÍSTICA ESTRATÉGICA Y GESTIÓN EN LA CADENA DE SUMINISTRO - 1ª VERSIÓN",
        description:
          "La maestría tiene como propósito, proporcionar a los estudiantes los conocimientos, habilidades y herramientas necesarias para diseñar, implementar y gestionar sistemas logísticos eficientes y efectivos en diversas organizaciones; formando profesionales altamente calificados y preparados para enfrentar los desafíos y aprovechar las oportunidades en el ámbito de la gestión de la cadena de suministro en un entorno empresarial cada vez más complejo y globalizado.",
        requirements: [
          "Carta de solicitud de inscripción dirigido al Director de Posgrado",
          "Ficha de inscripción",
          "Compromiso de Estudios",
          "Currículum Vitae(no documentado)",
          "Carnet de Identidad(anverso y reverso)",
          "Diploma Académico o Título en Provisión Nacional(anverso y reverso)(Solo para prosefionales)",
        ],
        details_raw: [
          "Grado Académico:Maestria",
          "Costo por modulo:1.713,00 Bs",
          "Descuento:Pago al contado tiene un descuento del 10% del monto total.",
          "Modalidad:Profesionales",
          "Fecha de Inicio:07 de Agosto de 2025 - Inicio Confirmado!!!",
        ],
        details: {
          grado_académico: "Maestria",
          costo_por_modulo: "1.713,00 Bs",
          descuento:
            "Pago al contado tiene un descuento del 10% del monto total.",
          modalidad: ["Profesionales"],
          fecha_de_inicio: "07 de Agosto de 2025 - Inicio Confirmado!!!",
        },
      },
    },
  ],
  doctorados: [],
};
